CREATE TABLE IF NOT EXISTS films(
    id UUID PRIMARY KEY NOT NULL,
    title VARCHAR(156) NOT NULL CHECK (LENGTH(title) > 0 AND LENGTH(title) <= 150),
    description TEXT CHECK (LENGTH(description) > 0 AND LENGTH(description) <= 1000),
    release_date TIMESTAMP,
    rating INTEGER CHECK(rating>=0 AND rating<=10) DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS film_actors(
    id UUID PRIMARY KEY NOT NULL,
    film_id UUID NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    actor_id UUID NOT NULL REFERENCES actors(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);